baseURL = "https://ivanhawkes.github.io/"
#baseURL = "https://www.hawkes.info/"
languageCode = "en-us"
theme = "hawkes-hugo-theme"
title = "Life Reboot"
themesDir = "themes"
MetaDataFormat = "toml"
DefaultContentLanguage = "en"
Paginate = 10

# Code highlighting.
pygmentsCodeFences = true

# Preserve special characters in taxonomy names ("Gérard Depardieu" vs "Gerard Depardieu")
preserveTaxonomyNames = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  fileName = "sitemap.xml"

[params.sitedesign]
  homepage = "/img/site/masthead/homepage.jpg"
  page = "/img/site/masthead/page.jpg"

[params.author]
  Name = "Ivan Hawkes"
  description = "Mostly harmless. (he / him) (true neutral)"
  homepage = "http://hawkes.info/"
  avatar = "/img/author/ivan-hawkes.png"

[params.copyright]
  year = "2021"
  owner = "Ivan Hawkes"
  notice = "all rights reserved."

[params.social]
	facebook = "ivan.hawkes"
	linkedin = "ivan-hawkes-a8386338"
	youtube = "channel/UClCTxhonVVsYb7qmqv4dldg"
	github = "ivanhawkes"
	bitbucket = "ivanhawkes"
	pinterest = "ivanhawkes"
  
[menu]
	[[menu.nav]]
	Pre = "<i class='bi-stickies'></i>"
	Name = "Posts"
	URL = "post"
	Weight = 1

	[[menu.nav]]
	Pre = "<i class='bi-kanban'></i>"
	Name = "Our Projects"
	URL = "project"
	Weight = 2

	[[menu.nav]]
	Pre = "<i class='bi-file-earmark-person'></i>"
	Name = "Our Team"
	URL = "profile"
	Weight = 3
	
	[[menu.nav]]
	Pre = "<i class='bi-egg-fried'></i>"
	Name = "Recipes"
	URL = "recipe"
	Weight = 4

	[[menu.nav]]
	Pre = "<i class='bi-tree'></i>"
	Name = "Garden"
	URL = "garden"
	Weight = 5
	
	[[menu.nav]]
	Pre = "<i class='bi-person-lines-fill'></i>"
	Name = "About Us"
	URL = "about"
	Weight = 7
